jcognet/airtable_sf

- back/src/Service/AirTable/AirtableClient.php
- back/src/Service/AirTable/LuClient.php
- back/src/Service/AirTable/SujetClient.php
- back/src/Service/Builder/ArticleBuilder.php
- back/src/Service/Builder/BuilderInterface.php
- back/src/Service/Builder/SujetBuilder.php
- back/src/Service/Repository/SujetList.php
- back/src/ValueObject/Article.php
- back/src/ValueObject/Sujet.php
- back/templates/email/block/article.html.twig
> feat: add sujet to article

- back/config/services.yaml
- back/src/Service/AirTable/Article/ALireClient.php
- back/src/Service/AirTable/Article/LuClient.php
- back/src/Service/AirTable/Article/SujetClient.php
- back/src/Service/AirTable/Biere/BiereClient.php
- back/src/Service/AirTable/Biere/BiereTypeClient.php
- back/src/Service/AirTable/Biere/BrasserieClient.php
- back/src/Service/Builder/Article/ArticleBuilder.php
- back/src/Service/Builder/Article/SujetBuilder.php
- back/src/Service/Builder/Biere/BiereBuilder.php
- back/src/Service/Builder/Biere/BiereTypeBuilder.php
- back/src/Service/Builder/Biere/BrasserieBuilder.php
- back/src/Service/NewsHandler.php
- back/src/Service/Repository/Article/SujetRepository.php
- back/src/Service/Repository/Biere/BiereTypeRepository.php
- back/src/Service/Repository/Biere/BrasserieRepository.php
- back/src/ValueObject/Article/Article.php
- back/src/ValueObject/Article/ArticleList.php
- back/src/ValueObject/Article/Sujet.php
- back/src/ValueObject/Biere/Biere.php
- back/src/ValueObject/Biere/BiereType.php
- back/src/ValueObject/Biere/Brasserie.php
- back/templates/email/block/article.html.twig
- back/templates/email/block/biere.html.twig
> feat: add biere block

- back/src/Service/Builder/Article/ArticleBuilder.php
- back/src/ValueObject/Article/Article.php
- back/templates/email/block/list_article.html.twig
> feat: add titre for article

- back/src/Service/Mailer/Sender.php
- back/templates/base.html.twig
> feat: add now to mailing

- back/src/Service/AirTable/Article/ALireClient.php
- back/src/Service/AirTable/Article/LuClient.php
- back/src/Service/AirTable/Biere/BiereClient.php
- back/src/Service/Block/Article/ArticleListALireBlockManager.php
- back/src/ValueObject/Article/ArticleList.php
- back/templates/email/block/list_article.html.twig
- back/templates/email/block/list_todo.html.twig
> feat: add nb articles to read

- back/templates/email/block/article.html.twig
- back/templates/email/block/biere.html.twig
- back/templates/email/block/image_url.html.twig
- back/templates/email/block/list_article.html.twig
- back/templates/email/block/list_todo.html.twig
- back/templates/email/block/video.html.twig
- back/templates/email/sujets.html.twig
> feat: cast block type in twig

- back/composer.json
- back/composer.lock
- back/config/bundles.php
- back/config/packages/dev/web_profiler.yaml
- back/config/packages/test/web_profiler.yaml
- back/config/routes/dev/web_profiler.yaml
- back/src/Exception/MethodNotUsableException.php
- back/src/Service/AirTable/AbstractClient.php
- back/src/Service/AirTable/Article/ALireClient.php
- back/src/Service/AirTable/Article/LuClient.php
- back/src/Service/AirTable/Article/SujetClient.php
- back/src/Service/AirTable/Biere/BiereClient.php
- back/src/Service/AirTable/Biere/BiereTypeClient.php
- back/src/Service/AirTable/Biere/BrasserieClient.php
- back/src/Service/AirTable/ToDo/ItemClient.php
- back/src/Service/Block/Article/ArticleListALireBlockManager.php
- back/symfony.lock
> Feat improve randomness

- back/src/Service/AirTable/AbstractClient.php
- back/src/Service/AirTable/Article/ImageClient.php
- back/src/Service/Block/Article/ImageManager.php
- back/src/Service/Builder/Article/ImageBuilder.php
- back/src/Service/NewsHandler.php
- back/src/ValueObject/Article/Image.php
- back/templates/email/block/article.html.twig
- back/templates/email/block/image.html.twig
> feat: add image block

- back/composer.json
- back/composer.lock
- back/src/Controller/GitController.php
- back/src/Service/Git/Deploy.php
- back/src/ValueObject/Git/Command.php
- back/templates/email/block/list_book.html.twig
- back/templates/email/git.html.twig
> Feat add cd

- .gitignore
- back/.env
- back/config/services.yaml
- back/src/Controller/GitController.php
- back/src/Service/Git/Deploy.php
> feat: improve deploy

- back/src/Service/AirTable/AbstractClient.php
> fix: protect data random

- Makefile
- back/.gitignore
- back/composer.json
- back/composer.lock
- back/config/services.yaml
- back/src/Extension/TagExtension.php
- back/src/Service/Git/Deploy.php
- back/src/Service/Git/TagReader.php
- back/src/Service/Git/TagWriter.php
- back/templates/base.html.twig
- back/templates/email/footer.html.twig
> feat: add tag in template

- back/config/services.yaml
- back/src/Service/Block/Google/InProgressContentManager.php
- back/src/Service/Block/Random/RandomPicBlockManager.php
- back/src/Service/Repository/Random/CatRepository.php
- back/src/Service/Repository/Random/FoxRepository.php
- back/src/Service/Repository/Random/RandomImageRepositoryInterface.php
- back/src/Service/Repository/Random/StarRepository.php
- back/src/ValueObject/NewsletterBlockManager/BlockType.php
> chore: update random manager

- back/config/blocks/default.yaml
- back/config/blocks/saturday.yaml
- back/config/packages/framework.yaml
- back/src/Service/AirTable/AbstractClient.php
- back/src/Service/Block/Article/ArticleListALireBlockManager.php
- back/src/Service/Block/Random/RgsenManager.php
- back/src/Service/Builder/Random/CriteriaBuilder.php
- back/src/Service/Converter/ConvertBlockTypeToManagerType.php
- back/src/Service/Repository/Random/RgsenRepository.php
- back/src/ValueObject/NewsletterBlockManager/BlockType.php
- back/src/ValueObject/NewsletterBlockManager/ManagerType.php
- back/src/ValueObject/Random/Criteria.php
- back/src/ValueObject/Random/CriteriaList.php
- back/templates/email/block/rgsen.html.twig
> feat: add rgsen

- back/bin/commandExportGoogle.php
- back/bin/commandOvh.php
- back/bin/defaultCommand.php
> feat: refacto ovh command

- back/src/Service/AirTable/ToDo/ItemClient.php
- back/templates/email/block/list_todo.html.twig
> feat: Update todo design

- back/src/Service/Builder/Article/ArticleBuilder.php
- back/src/ValueObject/Article/Article.php
- back/src/ValueObject/Article/ArticleList.php
- back/src/ValueObject/Article/ArticleType.php
- back/templates/email/block/list_article.html.twig
> feat: add icon in article list

- back/src/Controller/TestMailController.php
- back/src/Service/NewsletterManager/ConfigSelector.php
- back/src/Service/NewsletterManager/Manager.php
- back/src/ValueObject/NewsletterBlockManager/ManagerType.php
> feat: Add all block page

- back/composer.json
- back/composer.lock
- back/config/bundles.php
- back/config/packages/security.yaml
- back/config/packages/test/security.yaml
- back/symfony.lock
> feat: add access protection

- back/src/Service/AirTable/AbstractClient.php
- back/src/Service/Block/Article/ArticleListALireBlockManager.php
> fix: handle pagination

- back/composer.json
- back/composer.lock
- back/public/.htaccess
- back/symfony.lock
> feat: add .htaccess for Apache

- back/composer.json
- back/composer.lock
- back/config/blocks/default.yaml
- back/config/bundles.php
- back/src/Service/Block/Article/ArticleReadListBlockManager.php
- back/src/Service/Converter/ConvertBlockTypeToManagerType.php
- back/src/ValueObject/Article/AbstractArticleList.php
- back/src/ValueObject/Article/ArticleReadList.php
- back/src/ValueObject/NewsletterBlockManager/BlockType.php
- back/src/ValueObject/NewsletterBlockManager/ManagerType.php
- back/symfony.lock
- back/templates/email/block/list_article_read.html.twig
> feat: add article read

- back/templates/email/block/list_article.html.twig
- back/templates/email/block/list_article_read.html.twig
- back/templates/email/macro/article.html.twig
> feat: add article type macro

- back/config/blocks/default.yaml
- back/config/packages/framework.yaml
- back/src/Service/Block/Random/GoodPracticeOrganizationManager.php
- back/src/Service/Builder/Random/GoodPracticeBuilder.php
- back/src/Service/Converter/ConvertBlockTypeToManagerType.php
- back/src/Service/Repository/Random/GoodPracticeOrganizationRepository.php
- back/src/Service/Repository/Random/RgsenRepository.php
- back/src/ValueObject/NewsletterBlockManager/BlockType.php
- back/src/ValueObject/NewsletterBlockManager/ManagerType.php
- back/src/ValueObject/Random/GoodPractice.php
- back/src/ValueObject/Random/GoodPracticesList.php
- back/templates/email/block/good_practice_organization.html.twig
> feat: add good practice organization

- back/src/Service/AirTable/ToDo/ItemClient.php
- back/src/Service/Export/ExportToSpreadsheet.php
> feat: add export done to do

- back/src/Controller/TestMailController.php
- back/src/Service/NewsletterManager/Manager.php
- back/templates/email/block/list_inr_tool.html.twig
> fix: inr tools

- back/config/blocks/default.yaml
- back/src/Service/AirTable/Article/InterestingTopicClient.php
- back/src/Service/Block/Article/InterestingTopicListBlockManager.php
- back/src/Service/Builder/Article/InterestingTopicBuilder.php
- back/src/Service/Converter/ConvertBlockTypeToManagerType.php
- back/src/ValueObject/Article/InterestingTopic.php
- back/src/ValueObject/Article/InterestingTopicList.php
- back/src/ValueObject/NewsletterBlockManager/BlockType.php
- back/src/ValueObject/NewsletterBlockManager/ManagerType.php
- back/templates/email/block/list_interesting_topic.html.twig
> feat: add intereting topics

- back/templates/email/block/list_beer.html.twig
> feat: add good beer margin

- back/templates/email/block/list_article_read.html.twig
> fix: force 33% read article

- back/src/Service/AirTable/Article/ALireClient.php
- back/src/Service/AirTable/Article/LuClient.php
- back/src/Service/Builder/Article/AbstractArticleBuilder.php
- back/src/Service/Builder/Article/ArticleReadBuilder.php
- back/src/Service/Builder/Article/ArticleToReadBuilder.php
- back/src/Service/Builder/Article/InterestingTopicBuilder.php
- back/src/ValueObject/Article/Article.php
- back/templates/email/block/list_article_read.html.twig
> feat: article url

- back/composer.lock
- back/config/packages/framework.yaml
- back/src/Service/Export/ExportToSpreadsheet.php
- back/src/Service/Repository/Random/GithubRepository.php
> feat: show github nb issues

- back/src/Service/Export/ExportToSpreadsheet.php
- back/src/Service/Repository/Random/GithubRepository.php
- docker/php/Dockerfile
- docker/php/etc/php.ini
> feat: Up max exec tim

- back/src/Service/Git/Deploy.php
- back/templates/email/git.html.twig
> Feat update email deploy

- back/src/Service/Builder/Article/AbstractArticleBuilder.php
- back/src/Service/Builder/Beer/BeerBuilder.php
- back/src/ValueObject/Beer/Beer.php
- back/templates/email/block/list_beer.html.twig
> fix: beer image link + add link to beer

- back/src/Controller/TestExportController.php
- back/src/Service/Export/ExportToSpreadsheet.php
- back/src/Service/Repository/Random/CurrencyRepository.php
- back/src/Service/Repository/Random/GithubRepository.php
- back/templates/export/show.html.twig
> feat: add route test export

- back/src/Command/NewspaperHandlerCommand.php
- back/src/Service/Builder/Book/BookBuilder.php
- back/src/Service/Mailer/ErrorSender.php
- back/src/Service/Mailer/NewspaperSender.php
- back/src/Service/NewsletterManager/Manager.php
- back/templates/email/error.html.twig
> feat: send mail when the command fails

- back/src/Service/AirTable/ToDo/ItemClient.php
> feat: only show in progress item

- back/src/Service/Builder/Article/AbstractArticleBuilder.php
- back/src/Service/NewsletterManager/Manager.php
- back/src/ValueObject/Article/Article.php
- back/src/ValueObject/Article/Concept.php
- back/templates/email/block/article.html.twig
> feat: show if article has no concept

- back/src/Controller/TestMailController.php
- back/src/Service/Block/Random/InrManager.php
- back/src/Service/Builder/Random/InrToolBuilder.php
- back/src/ValueObject/Article/Concept.php
- back/templates/email/block/article.html.twig
- back/templates/email/block/list_article_read.html.twig
- back/templates/email/block/list_todo.html.twig
- back/templates/email/macro/article.html.twig
- back/templates/email/newsletter.html.twig
> Feat add no concept to article list block

- back/src/Service/AirTable/Article/ConceptClient.php
- back/src/Service/Export/ExportToSpreadsheet.php
- back/src/ValueObject/Article/Concept.php
- back/src/ValueObject/NewsletterBlockManager/BlockType.php
> feat: add concept to export

- back/config/blocks/default.yaml
- back/src/Extension/PhpExtension.php
- back/src/Service/AirTable/AbstractClient.php
- back/src/Service/AirTable/Article/ConceptClient.php
- back/src/Service/Block/Article/ConceptManager.php
- back/src/Service/Builder/Article/ConceptBuilder.php
- back/src/Service/Converter/ConvertBlockTypeToManagerType.php
- back/src/ValueObject/Article/Concept.php
- back/src/ValueObject/NewsletterBlockManager/ManagerType.php
- back/templates/email/block/concept.html.twig
- back/templates/email/macro/article.html.twig
> feat: add concept block

- back/src/Controller/GitController.php
- back/src/Service/Git/Deploy.php
- back/src/Service/Git/TagHandler.php
> feat: add deploy route info data

- back/config/blocks/sunday.yaml
- back/src/Service/Block/Google/CurreniesManager.php
- back/src/Service/Converter/ConvertBlockTypeToManagerType.php
- back/src/ValueObject/Article/Concept.php
- back/src/ValueObject/NewsletterBlockManager/BlockType.php
- back/src/ValueObject/NewsletterBlockManager/ManagerType.php
- back/src/ValueObject/Random/ListImageUrl.php
- back/templates/email/block/list_image_url.html.twig
> feat: add currencies result

- .gitignore
- back/config/services.yaml
- back/src/Command/NewspaperHandlerCommand.php
- back/src/Controller/TestMailController.php
- back/src/Service/Archive/DataInputOuputHandler.php
- back/src/Service/Mailer/NewspaperSender.php
- back/src/Service/NewsletterManager/Creater.php
- back/src/Service/NewsletterManager/Manager.php
> feat: save newsletter in json

- back/src/Command/NewspaperHandlerCommand.php
- back/src/Controller/TestMailController.php
- back/src/Service/Archive/DataInputOuputHandler.php
- back/src/Service/NewsletterManager/Manager.php
- back/src/ValueObject/Archive/NewsLetter.php
> feat: handle was sent

- back/bin/commandCleanArchive.php
- back/src/Command/CleanDataCommand.php
- back/src/Controller/TestMailController.php
- back/src/Service/Archive/Cleaner.php
> feat: clean old archive

- back/config/packages/security.yaml
- back/config/services.yaml
- back/src/Controller/ImageController.php
- back/src/Controller/TestExportController.php
- back/src/Service/Picture/ImageInPathLister.php
- back/src/ValueObject/Picture/Directory.php
- back/src/ValueObject/Picture/Picture.php
- back/templates/base.html.twig
- back/templates/img/list.html.twig
- back/tests/Functionnal/Controller/ImageControllerTest.php
> feat: add image handling

- back/config/blocks/default.yaml
- back/config/blocks/sunday.yaml
- back/src/Service/Block/Google/CurrenciesManager.php
- back/src/Service/Block/Picture/PictureManager.php
- back/src/Service/Converter/ConvertBlockTypeToManagerType.php
- back/src/ValueObject/NewsletterBlockManager/BlockType.php
- back/src/ValueObject/NewsletterBlockManager/ManagerType.php
- back/src/ValueObject/Picture/Directory.php
- back/templates/email/block/image_list_pictures.html.twig
- back/templates/email/macro/article.html.twig
- back/templates/img/list.html.twig
- back/tests/Functionnal/Controller/ImageControllerTest.php
- back/tests/Functionnal/Controller/TestMailControllerTest.php
> fix: add return line

- back/src/Controller/GitController.php
> feat: add symfony version to git route

- back/phpunit.xml.dist
- back/src/Service/AirTable/UrlBuilder.php
- back/src/Service/Builder/Article/AbstractArticleBuilder.php
- back/src/Service/Builder/Beer/BeerBuilder.php
- back/src/Service/Builder/Book/BookBuilder.php
- back/src/ValueObject/Article/Article.php
- back/src/ValueObject/Beer/Beer.php
- back/src/ValueObject/Book/Book.php
- back/templates/email/block/article.html.twig
- back/templates/email/block/book.html.twig
- back/templates/email/block/list_article.html.twig
- back/templates/email/block/list_beer.html.twig
> feat: add airtable links to blocks

- back/config/services.yaml
- back/src/Controller/ImageController.php
- back/src/Enum/Picture/Format.php
- back/src/Exception/Picture/UnknownFormatException.php
- back/src/Service/FileNameGenerator.php
- back/src/Service/Picture/ThumbnailerGenerator.php
- back/src/Service/Picture/ThumbnailerGetter.php
- back/src/Service/Picture/ThumbnailerNameGetter.php
- back/src/ValueObject/NewsletterBlockManager/ManagerType.php
- back/templates/email/block/bird.html.twig
> feat: add thumbnail configuration

- back/config/blocks/default.yaml
- back/src/Enum/Picture/Format.php
- back/src/Exception/NewsletterBlockManager/UnknownManagerTypeException.php
- back/src/Service/Block/Lpo/ListBirdManager.php
- back/src/Service/Converter/ConvertBlockTypeToManagerType.php
- back/src/Service/Picture/ThumbnailerGenerator.php
- back/src/ValueObject/Lpo/ListBlockBird.php
- back/src/ValueObject/NewsletterBlockManager/BlockType.php
- back/src/ValueObject/NewsletterBlockManager/ManagerType.php
- back/templates/email/block/list_bird.html.twig
> feat: add bird list

- back/config/packages/security.yaml
- back/config/services.yaml
- back/src/Command/NewspaperHandlerCommand.php
- back/src/Controller/SecurityController.php
- back/src/Extension/NavigationExtension.php
- back/src/Service/NewsletterManager/Creater.php
- back/src/Service/NewsletterManager/Manager.php
- back/src/Service/Security/LoginLinkHandler.php
- back/templates/base.html.twig
> feat: add auto connect link

- back/config/packages/routing.yaml
> fix: add base url to router

- back/composer.json
- back/composer.lock
- back/config/packages/test/security.yaml
- back/config/routes/annotations.yaml
- back/config/routes/attributes.yaml
- back/rector.php
- back/src/Service/Block/Random/InrManager.php
- back/src/Service/NewsletterManager/Creater.php
- back/src/Service/NewsletterManager/Manager.php
- back/symfony.lock
- back/templates/email/block/bird.html.twig
- back/templates/email/block/image_list_pictures.html.twig
- back/templates/email/block/list_article.html.twig
- back/templates/email/block/list_bird.html.twig
- back/tests/Functionnal/Controller/TestMailControllerTest.php
> chores: update to SF 6.2

- back/bin/commandImportBird.php
> feat: add OVH command import bird

- back/config/blocks/saturday.yaml
- back/config/blocks/sunday.yaml
- back/src/Service/AirTable/Article/SeeAgainClient.php
- back/src/Service/Block/Article/ArticleSeeAgainListBlockManager.php
- back/src/Service/Builder/Article/AbstractArticleBuilder.php
- back/src/Service/Converter/ConvertBlockTypeToManagerType.php
- back/src/ValueObject/Article/AbstractArticleList.php
- back/src/ValueObject/Article/Article.php
- back/src/ValueObject/Article/ArticleSeeAgainList.php
- back/src/ValueObject/Article/Sujet.php
- back/src/ValueObject/NewsletterBlockManager/BlockType.php
- back/src/ValueObject/NewsletterBlockManager/ManagerType.php
- back/templates/email/block/article.html.twig
- back/templates/email/block/list_article_read.html.twig
- back/templates/email/block/see_again.html.twig
- back/tests/Functionnal/SetUserTrait.php
> feat: add see again block

- back/src/Service/AirTable/AbstractClient.php
- back/src/Service/Builder/Article/AbstractArticleBuilder.php
- back/src/Service/Builder/Article/ConceptBuilder.php
- back/src/ValueObject/Article/AbstractArticleList.php
- back/src/ValueObject/Article/Concept.php
- back/templates/email/block/concept.html.twig
- back/templates/email/block/list_article_read.html.twig
> feat: clean concept bloc

- back/config/packages/framework.yaml
- back/templates/email/block/next_runs.html.twig
> Feat switch api auth

- back/src/Exception/NewsletterBlockManager/UnknownBlockTypeException.php
- back/src/Exception/NewsletterBlockManager/UnknownConvertBlockTypeToManagerTypeException.php
- back/src/Service/Converter/ConvertBlockTypeToManagerType.php
- back/src/Service/NewsletterManager/ConfigSelector.php
- back/src/Service/NewsletterManager/Creater.php
- back/src/ValueObject/Article/Article.php
- back/src/ValueObject/Article/ArticleList.php
- back/src/ValueObject/Article/ArticleReadList.php
- back/src/ValueObject/Article/ArticleSeeAgainList.php
- back/src/ValueObject/Article/Concept.php
- back/src/ValueObject/Article/Image.php
- back/src/ValueObject/Article/InterestingTopicList.php
- back/src/ValueObject/Article/Video.php
- back/src/ValueObject/Beer/BeerList.php
- back/src/ValueObject/Book/Book.php
- back/src/ValueObject/Book/BookList.php
- back/src/ValueObject/Lpo/BlockBird.php
- back/src/ValueObject/Lpo/ListBlockBird.php
- back/src/ValueObject/Meteo/MeteoList.php
- back/src/ValueObject/NewsletterBlockManager/BlockType.php
- back/src/ValueObject/Picture/Directory.php
- back/src/ValueObject/Random/CriteriaList.php
- back/src/ValueObject/Random/GoodPracticesList.php
- back/src/ValueObject/Random/ImageUrl.php
- back/src/ValueObject/Random/InrToolList.php
- back/src/ValueObject/Random/ListImageUrl.php
- back/src/ValueObject/Run/ListBlockNextRun.php
- back/src/ValueObject/ToDo/ItemList.php
- back/src/ValueObject/Twitter/Message.php
- back/templates/email/newsletter.html.twig
> chore: migration BlockType to Enum

- back/config/blocks/default.yaml
- back/config/packages/framework.yaml
- back/config/services.yaml
- back/src/Service/Block/Random/Inr491Manager.php
- back/src/Service/Block/Random/InrManager.php
- back/src/Service/Builder/Inr/Inr491FamilleBuilder.php
- back/src/Service/Builder/Inr/Inr491ItemBuilder.php
- back/src/Service/Builder/Inr/Inr491RecommandationBuilder.php
- back/src/Service/Builder/Inr/InrToolBuilder.php
- back/src/Service/Converter/ConvertBlockTypeToManagerType.php
- back/src/Service/Repository/Random/Inr491Repository.php
- back/src/Service/Repository/Random/InrRepository.php
- back/src/ValueObject/Inr/BlockFamille.php
- back/src/ValueObject/Inr/Famille.php
- back/src/ValueObject/Inr/Inr491Item.php
- back/src/ValueObject/Inr/Inr491Recommandation.php
- back/src/ValueObject/Inr/InrTool.php
- back/src/ValueObject/Inr/InrToolList.php
- back/src/ValueObject/NewsletterBlockManager/BlockType.php
- back/src/ValueObject/NewsletterBlockManager/ManagerType.php
- back/templates/email/block/inr_491.html.twig
> feat: add rg 491 INR

- back/config/packages/framework.yaml
- back/config/packages/twig.yaml
- back/config/services.yaml
- back/src/Service/Repository/Random/GoodPracticeOrganizationRepository.php
- back/src/Service/Repository/Random/RgsenRepository.php
- back/src/ValueObject/Article/Image.php
- back/templates/email/block/bird.html.twig
- back/templates/email/block/good_practice_organization.html.twig
- back/templates/email/block/inr_491.html.twig
- back/templates/email/block/rgsen.html.twig
> feat: add base url for interesint service

- back/src/Service/Block/Picture/PictureManager.php
- back/src/Service/Picture/ImageInPathLister.php
- back/src/Service/Repository/Random/GoodPracticeOrganizationRepository.php
- back/src/Service/Repository/Random/RgsenRepository.php
- back/src/ValueObject/Article/Image.php
- back/templates/email/block/image_list_pictures.html.twig
> fix: change URL image in list_pictures block

- back/src/Service/Export/ExportToSpreadsheet.php
> feat: add unread article + article with no concept to export

- back/templates/email/newsletter.html.twig
> feat: add header block

- back/config/services.yaml
- back/src/Enum/Picture/Format.php
- back/src/Exception/Picture/ImageNotDownloadableException.php
- back/src/Service/Builder/Article/ImageBuilder.php
- back/src/Service/Builder/Beer/BeerBuilder.php
- back/src/Service/Builder/Picture/CachedImageBuilder.php
- back/src/Service/Picture/CachedImageDirectoryGetter.php
- back/src/Service/Picture/ImageDownloader.php
- back/src/Service/Picture/ThumbnailerGenerator.php
- back/src/ValueObject/Article/Image.php
- back/src/ValueObject/Beer/Beer.php
- back/src/ValueObject/Picture/CachedImage.php
- back/templates/email/block/image.html.twig
- back/templates/email/block/list_beer.html.twig
> feat: add cachable image

- back/config/packages/security.yaml
- back/templates/email/block/concept.html.twig
> chore: remove deprecated security 6.2

- back/composer.json
- back/composer.lock
- back/config/bundles.php
- back/config/packages/security.yaml
- back/phpunit.xml.dist
- back/src/Controller/Newsletter/ContentController.php
- back/src/Controller/Newsletter/ExportController.php
- back/src/ValueObject/AbstractBlock.php
- back/src/ValueObject/Book/BookList.php
- back/templates/email/newsletter.html.twig
- back/tests/Functionnal/Controller/Newsletter/ContentControllerTest.php
> feat: rename route

- back/src/Command/NewspaperHandlerCommand.php
- back/src/Service/Mailer/NewsletterSender.php
> chore: newsletter vs newspaper

- back/config/packages/security.yaml
- back/config/services.yaml
- back/src/Controller/Newspaper/ContentController.php
- back/src/Controller/Page/DashboardController.php
- back/src/Enum/Picture/Format.php
- back/src/Service/Block/BlockFinder.php
- back/src/Service/Page/MainImageFetcher.php
- back/templates/dashboard/show.html.twig
> feat: show current newsletter'

- back/src/Controller/Page/DashboardController.php
- back/templates/page/base.html.twig
> feat: add last deploy to dashboard

- back/config/services.yaml
- back/src/Command/NewspaperHandlerCommand.php
- back/src/Command/Test/CreateAllJsonCommand.php
- back/src/Controller/Page/DashboardController.php
- back/src/Enum/Picture/Format.php
- back/src/Extension/NavigationExtension.php
- back/src/Service/Archive/NewsletterWriterFetcher.php
- back/src/Service/Archive/PreviousNewsletterFetcher.php
- back/src/Service/Block/BlockFinder.php
- back/src/Service/Git/Deploy.php
- back/src/Service/NewsletterManager/Manager.php
- back/src/Service/Page/BotDouxFetcher.php
- back/templates/dashboard/show.html.twig
> feat: shat last newspaper to dashboard

- back/src/Controller/Page/DashboardController.php
- back/src/Service/Archive/PreviousNewsletterFetcher.php
- back/src/Service/Export/Exporter.php
- back/src/ValueObject/Random/Currency.php
- back/templates/dashboard/show.html.twig
> fix: previous date in dashboard

- back/config/packages/security.yaml
> fix: security in img routes

- back/src/Service/Picture/DirectoryLister.php
- back/src/ValueObject/Picture/Directory.php
- back/templates/dashboard/include/current_newspaper.html.twig
- back/templates/dashboard/include/directory_img.html.twig
- back/templates/dashboard/show.html.twig
> fix: sort directory image in dashboard

- back/src/Command/CleanDataCommand.php
- back/src/Command/ExportDataCommand.php
- back/src/Command/Lpo/LpoPdfFetchCommand.php
- back/src/Command/NewspaperHandlerCommand.php
> chore: remove deprecation in commands

- back/config/blocks/saturday.yaml
- back/config/blocks/sunday.yaml
- back/src/Command/NewspaperHandlerCommand.php
- back/src/Service/Export/Exporter.php
- back/src/Service/Mailer/ErrorSender.php
- back/src/Service/Picture/RandomPictorySelector.php
- back/src/Service/Twitter/TwitterClient.php
- back/src/ValueObject/Article/InterestingTopicList.php
- back/templates/dashboard/include/current_newspaper.html.twig
- back/templates/dashboard/include/interesting_topic_list.html.twig
> feat: add interesting topic count to export

- back/src/Extension/NavigationExtension.php
- back/src/Service/Page/ArticleSeeAgainListFetcher.php
- back/templates/dashboard/include/article_see_again.html.twig
- back/templates/dashboard/include/interesting_topic_list.html.twig
- back/templates/dashboard/show.html.twig
> feat: add see again block in dashboard

- back/composer.json
- back/composer.lock
- back/templates/dashboard/include/article_see_again.html.twig
- back/templates/dashboard/include/current_newspaper.html.twig
- back/templates/newsletter/block/article.html.twig
- back/templates/newsletter/block/book.html.twig
- back/templates/newsletter/block/concept.html.twig
- back/templates/newsletter/block/video.html.twig
> feat: add markdown engine

- back/src/Extension/NavigationExtension.php
- back/src/Service/Page/MeteoListFetcher.php
- back/templates/dashboard/include/meteo.html.twig
- back/templates/dashboard/show.html.twig
> feat: add meteo to dashboard

- back/templates/dashboard/include/current_newspaper.html.twig
> feat: add kpi to dashboard

- back/templates/question/answer.html.twig
> feat: add more link to answer

- back/src/Service/Block/Question/QuestionManager.php
> fix: use question lister instead of querying AT

- back/src/Service/Export/Exporter.php
> feat: add question numbers in export

- back/templates/question/answer.html.twig
- back/tests/Functionnal/Controller/Page/Question/QuestionControllerTest.php
> chore: add test to question

- back/composer.lock
- back/src/Controller/Page/Question/QuestionController.php
- back/src/Service/AirTable/AbstractClient.php
- back/src/Service/AirTable/AirtableClient.php
- back/src/Service/AirTable/Qcm/QuestionsClient.php
- back/src/Service/Block/Question/QuestionManager.php
- back/src/Service/Builder/Qcm/QuestionBuilder.php
- back/src/Service/Import/Airtable/Qcm/Question/QuestionLister.php
- back/tests/Functionnal/Controller/Page/Question/QuestionControllerTest.php
> feat: update date use for QCM

- back/composer.lock
- back/phpunit.xml.dist
- back/src/Service/Block/Question/QuestionManager.php
- back/src/Service/Import/Airtable/Qcm/Question/QuestionLister.php
> feat: return random last used questions'

- back/src/Controller/Page/DashboardController.php
- back/src/Extension/NavigationExtension.php
- back/src/Service/Import/Airtable/Qcm/Question/Fetcher.php
- back/src/Service/Page/RandomPicFetcher.php
- back/templates/dashboard/holiday.html.twig
- back/templates/dashboard/include/random_image.html.twig
> feat: update dashboard to holiday

- back/composer.lock
- back/config/blocks/holiday.yaml
- back/src/Service/NewsletterManager/ConfigSelector.php
> feat: update newsletter holiday

- back/config/services.yaml
- back/templates/newsletter/block/quiz.html.twig
> fix: url question in newsletter

- back/src/ValueObject/Archive/NewsLetter.php
- back/tests/Functionnal/Command/NewspaperHandlerCommandTest.php
- back/tests/Functionnal/Controller/GitControllerTest.php
- back/tests/Functionnal/Controller/ImageControllerTest.php
- back/tests/Functionnal/Controller/ImportControllerTest.php
- back/tests/Functionnal/Controller/Newsletter/ContentControllerTest.php
- back/tests/Functionnal/Controller/Newspaper/ContentControllerTest.php
- back/tests/Functionnal/Controller/Page/DashboardControllerTest.php
- back/tests/Functionnal/Controller/Page/Question/QuestionControllerTest.php
> chore: add test to command to create newsletter

- back/config/services.yaml
- back/src/Controller/Page/ListImportedDataController.php
- back/src/Exception/Import/Airtable/NoFileYamlException.php
- back/src/Exception/Import/Airtable/UnknownDataImportedTypeException.php
- back/src/Service/Contract/AirtableConfigInterface.php
- back/src/Service/Import/Airtable/Article/ALire/Config.php
- back/src/Service/Import/Airtable/Article/ALire/Lister.php
- back/src/Service/Import/Airtable/Article/ALire/list.yaml
- back/src/Service/Import/Airtable/ConfigFactory.php
- back/src/Service/Import/Airtable/Holiday/Holiday/Config.php
- back/src/Service/Import/Airtable/Holiday/Holiday/Fetcher.php
- back/src/Service/Import/Airtable/ImportedDataFactory.php
- back/src/Service/Import/Airtable/IsImported.php
- back/src/Service/Import/Airtable/IsListable.php
- back/src/Service/Import/Airtable/Qcm/Question/Config.php
- back/src/Service/Import/Airtable/Run/NextRun/Config.php
- back/src/Service/Import/Airtable/YamlListReader.php
- back/src/ValueObject/Import/Airtable/Field.php
- back/src/ValueObject/Import/Airtable/ImportedData.php
- back/templates/list_imported_data/show.html.twig
> feat: add list screen

- back/src/Controller/Page/ListImportedDataController.php
- back/src/Exception/Import/Airtable/UnknownListServiceException.php
- back/src/Service/Import/Airtable/ImportedDataFactory.php
- back/templates/list_imported_data/show.html.twig
- back/tests/Functionnal/Command/NewspaperHandlerCommandTest.php
- back/tests/Functionnal/Controller/GitControllerTest.php
- back/tests/Functionnal/Controller/ImageControllerTest.php
- back/tests/Functionnal/Controller/ImportControllerTest.php
- back/tests/Functionnal/Controller/Newsletter/ContentControllerTest.php
- back/tests/Functionnal/Controller/Newspaper/ContentControllerTest.php
- back/tests/Functionnal/Controller/Page/DashboardControllerTest.php
- back/tests/Functionnal/Controller/Page/ListImportedDataControllerTest.php
- back/tests/Functionnal/Controller/Page/Question/QuestionControllerTest.php
> chore: add list test & clean code

- back/src/Controller/Page/ListImportedDataController.php
- back/src/Enum/Import/Airtable/Order.php
- back/src/Exception/Import/Airtable/UnknownFieldException.php
- back/src/Extension/NavigationExtension.php
- back/src/Service/Import/Airtable/AbstractLister.php
- back/src/Service/Import/Airtable/Article/ALire/list.yaml
- back/src/Service/Import/Airtable/ImportedDataFactory.php
- back/src/Service/Import/Airtable/YamlListReader.php
- back/src/ValueObject/Import/Airtable/Field.php
- back/src/ValueObject/Import/Airtable/Sort.php
- back/templates/list_imported_data/show.html.twig
- back/tests/Functionnal/Controller/Page/ListImportedDataControllerTest.php
> feat: add sortable field

- back/config/services.yaml
- back/src/Service/AirTable/Article/SeeAgainClient.php
- back/src/Service/Block/Article/ArticleSeeAgainListBlockManager.php
- back/src/Service/Import/Airtable/Article/SeeAgain/Config.php
- back/src/Service/Import/Airtable/Article/SeeAgain/Fetcher.php
- back/src/Service/Import/Airtable/Article/SeeAgain/Importer.php
- back/src/Service/Import/Airtable/Article/SeeAgain/Lister.php
- back/src/Service/Import/Airtable/Article/SeeAgain/list.yaml
- back/src/Service/Import/Airtable/ImportedDataFactory.php
- back/templates/list_imported_data/show.html.twig
> feat: add import & list for see again

- back/src/Service/Import/Airtable/ConfigFactory.php
- back/src/Service/Import/Airtable/IsImported.php
- back/src/Service/Import/Airtable/IsListable.php
- back/templates/list_imported_data/show.html.twig
> feat: show readble name in men

- back/src/Exception/Builder/UnknownArticleBuilderException.php
- back/src/Service/Builder/Article/AbstractArticleBuilder.php
> fix: correct URL article builder

- back/src/Controller/Page/DashboardController.php
- back/src/Controller/Page/ListImportedDataController.php
- back/src/Controller/Page/Question/QuestionController.php
- back/templates/page/base.html.twig
> feat: add dynamic title

- back/config/packages/security.yaml
- back/src/Controller/ImageController.php
- back/templates/dashboard/include/directory_img.html.twig
- back/templates/img/list.html.twig
- back/templates/include/image.html.twig
> feat: add route for picture front

- back/composer.lock
- back/src/Controller/Page/DashboardController.php
- back/src/Service/Holiday/IsHolidayDeterminator.php
- back/templates/dashboard/holiday.html.twig
- back/templates/dashboard/include/list_imported_data.html.twig
- back/templates/list_imported_data/show.html.twig
> feat: add link to dashboard

- back/templates/include/image.html.twig
> fix:image format in image list

- back/rector.php
- back/src/Command/Airtable/ImportCommand.php
- back/src/Service/Import/Airtable/AllImporter.php
> feat: allow import only one data

- back/composer.lock
- back/config/services.yaml
- back/rector.php
- back/src/Controller/Page/ListImportedDataController.php
- back/src/Exception/Import/Airtable/UnknownFilterServiceException.php
- back/src/Service/Import/Airtable/AbstractFilter.php
- back/src/Service/Import/Airtable/Article/SeeAgain/Filter.php
- back/src/Service/Import/Airtable/Article/SeeAgain/list.yaml
- back/src/Service/Import/Airtable/Factory/ConfigFactory.php
- back/src/Service/Import/Airtable/Factory/ImportedDataFactory.php
- back/src/Service/Import/Airtable/Factory/ImportedDataFilterFactory.php
- back/src/Service/Import/Airtable/Factory/ImportedDataListFactory.php
- back/src/Service/Import/Airtable/IsFiltrable.php
- back/src/Service/Import/Airtable/IsListable.php
- back/src/Service/Import/Airtable/YamlListReader.php
- back/src/ValueObject/Import/Airtable/Filter.php
- back/templates/list_imported_data/show.html.twig
> feat: add filtrable notion

- back/src/Controller/Page/ListImportedDataController.php
- back/src/Service/Import/Airtable/YamlListReader.php
- back/templates/list_imported_data/include/data_table.html.twig
- back/templates/list_imported_data/show.html.twig
> feat: add ajax route

- back/src/Controller/Page/ListImportedDataController.php
- back/src/Service/Import/Airtable/AbstractFilter.php
- back/src/Service/Import/Airtable/AbstractLister.php
- back/src/Service/Import/Airtable/Article/SeeAgain/Filter.php
- back/src/Service/Import/Airtable/Factory/ImportedDataFactory.php
- back/src/Service/Normalizer/Picture/DirectoryDenormalizer.php
- back/src/Service/Normalizer/Picture/PictureDenormalizer.php
> feat: add filters to list

- back/public/js/ListImportedData.js
- back/public/js/data/ListImportedData.js
- back/public/js/ui/ListImportedData.js
- back/templates/list_imported_data/include/data_table.html.twig
- back/templates/list_imported_data/show.html.twig
- back/templates/page/base.html.twig
> feat: add fetch js

- back/composer.lock
- back/public/css/pages/showcase.css
- back/public/js/data/ListImportedData.js
- back/public/js/ui/ListImportedData.js
- back/public/js/ui/loader.js
- back/templates/list_imported_data/show.html.twig
- back/templates/page/base.html.twig
> feat: add js loader

- back/composer.json
- back/composer.lock
- back/public/css/pages/showcase.css
- back/src/Controller/Page/Fooding/HealthController.php
- back/src/Service/Builder/Fooding/CoffeeBuilder.php
- back/src/Service/Fooding/ConsumptionGetter.php
- back/src/Service/Import/Airtable/Fooding/Coffee/Fetcher.php
- back/src/Service/Import/Airtable/Fooding/Meat/Fetcher.php
- back/src/Service/Normalizer/Fooding/CoffeeDenormalizer.php
- back/src/Service/Normalizer/Fooding/MeatDenormalizer.php
- back/src/ValueObject/Fooding/Coffee.php
- back/src/ValueObject/Fooding/MonthList.php
- back/templates/fooding/health.html.twig
- back/tests/Functionnal/Controller/Fooding/HealthControllerTest.php
> feat: show coffe in page

- back/src/Controller/Page/Fooding/HealthController.php
- back/templates/fooding/health.html.twig
> feat: add icon navigation for fooding

- back/public/js/ui/FoodingHealth.js
- back/src/ValueObject/Fooding/MonthList.php
- back/templates/fooding/include/data.html.twig
> feat: add month summary

- back/composer.lock
- back/src/Controller/Page/Fooding/HealthController.php
- back/src/Service/Fooding/ConsumptionLister.php
- back/src/ValueObject/Fooding/MonthList.php
- back/templates/dashboard/include/current_newspaper.html.twig
- back/templates/fooding/list.html.twig
> feat: fooding add month summary

- back/bin/defaultCommand.php
- back/composer.json
- back/composer.lock
- back/config/bundles.php
- back/rector.php
- back/src/Controller/ImageController.php
- back/src/Exception/Picture/DirectoryNotFoundException.php
- back/src/Extension/NavigationExtension.php
- back/src/Service/Builder/Inr/Inr491ItemBuilder.php
- back/src/Service/Git/Deploy.php
- back/src/Service/Import/Airtable/File/File/Importer.php
- back/src/Service/Import/Lpo/BirdPdfImporter.php
- back/src/Service/Picture/ImageInPathLister.php
- back/src/ValueObject/Article/Video.php
- back/templates/dashboard/include/directory_img.html.twig
- back/templates/img/list.html.twig
> feat: encrypt directory image url

- back/config/services.yaml
- back/src/Controller/Page/DashboardController.php
- back/src/Service/Alert/AlertManager.php
- back/src/Service/Alert/Alerter.php
- back/src/Service/Alert/AlerterInterface.php
- back/src/Service/Alert/Fooding/ColoringAlerter.php
- back/src/Service/Alert/Fooding/CutAlerter.php
- back/src/Service/Alert/Fooding/QiAlerter.php
- back/src/Service/Alert/ListAlertBlock.php
- back/src/Service/Import/Airtable/Fooding/Coloring/Fetcher.php
- back/src/Service/Import/Airtable/Fooding/Cut/Fetcher.php
- back/src/Service/Import/Airtable/Fooding/Qi/Fetcher.php
- back/src/Service/NewsletterManager/NewspaperCreator.php
- back/src/Service/Normalizer/Fooding/ColoringDenormalizer.php
- back/src/Service/Normalizer/Fooding/CutDenormalizer.php
- back/src/Service/Normalizer/Fooding/QiDenormalizer.php
- back/src/ValueObject/Alert/Alert.php
- back/src/ValueObject/Alert/LevelEnum.php
- back/src/ValueObject/Alert/ListAlert.php
- back/src/ValueObject/NewsletterBlockManager/BlockType.php
- back/src/ValueObject/NewsletterBlockManager/ManagerType.php
- back/templates/dashboard/holiday.html.twig
- back/templates/dashboard/show.html.twig
- back/templates/include/alerts.html.twig
- back/templates/newsletter/block/list_alert.html.twig
> feat: add alerting

- back/config/services.yaml
- back/src/Service/AirTable/Fooding/AbsClient.php
- back/src/Service/Alert/Fooding/AbsAlerter.php
- back/src/Service/Builder/Fooding/AbsBuilder.php
- back/src/Service/Fooding/AbsMissingCounter.php
- back/src/Service/Import/Airtable/Fooding/Abs/Config.php
- back/src/Service/Import/Airtable/Fooding/Abs/Fetcher.php
- back/src/Service/Import/Airtable/Fooding/Abs/Importer.php
- back/src/Service/Import/Airtable/Fooding/Abs/Lister.php
- back/src/Service/Import/Airtable/Fooding/Coloring/Fetcher.php
- back/src/Service/Import/Airtable/Fooding/Cut/Fetcher.php
- back/src/Service/Import/Airtable/Fooding/Qi/Fetcher.php
- back/src/Service/Normalizer/Fooding/AbsDenormalizer.php
- back/src/ValueObject/Fooding/Abs.php
> feat: add abs alert

- back/config/packages/framework.yaml
- back/config/services.yaml
- back/src/Service/Builder/Random/CriteriaBuilder.php
- back/src/Service/Repository/Random/RgesnRepository.php
- back/src/ValueObject/Random/Criteria.php
- back/templates/newsletter/block/rgesn.html.twig
> feat: update to RGESN V2

- back/src/Service/Alert/AlertManager.php
- back/src/Service/Alert/Alerter.php
- back/src/Service/Holiday/IsHolidayDeterminator.php
- back/src/Service/Meteo/PlaceFactory.php
> chore: remove null date

- back/src/Service/Alert/Fooding/AbsAlerter.php
- back/src/Service/Import/Airtable/Fooding/Abs/Fetcher.php
> fix: abs last occurence

- back/templates/export/show.html.twig
- back/tests/Functionnal/Controller/Newsletter/ExportControllerTest.php
> chore: test export controller

- back/src/Enum/Alert/LevelEnum.php
- back/src/Enum/Alert/TypeEnum.php
- back/src/Service/Alert/Fooding/CurrentAbsSeriesAlerter.php
- back/src/Service/Alert/Fooding/DaysWithoutCoffeeSeriesAlerter.php
- back/src/Service/Alert/Fooding/DaysWithoutMeatSeriesAlerter.php
- back/src/Service/Alert/Fooding/MaxAbsSeriesAlerter.php
- back/src/Service/Fooding/AbsSeriesCounter.php
- back/src/Service/Fooding/AbstractSeriesCounter.php
- back/src/Service/Fooding/CoffeeSeriesCounter.php
- back/src/Service/Fooding/MeatSeriesCounter.php
- back/src/Service/Import/Airtable/Fooding/Coffee/Fetcher.php
- back/src/Service/Import/Airtable/Fooding/Meat/Fetcher.php
- back/templates/alert/show.html.twig
- back/templates/include/alerts.html.twig
> feat: add positive alerts

- back/config/services.yaml
- back/src/Service/Builder/ToDo/ItemBuilder.php
- back/src/Service/Import/Airtable/AbstractImporter.php
- back/src/Service/Import/Airtable/Factory/ImportedDataListFactory.php
- back/src/Service/Import/Airtable/IsListable.php
- back/src/Service/Import/Airtable/ToDo/Item/Config.php
- back/src/Service/Import/Airtable/ToDo/Item/Fetcher.php
- back/src/Service/Import/Airtable/ToDo/Item/Importer.php
- back/src/Service/Import/Airtable/ToDo/Item/Lister.php
- back/src/Service/Import/Airtable/ToDo/Item/list.yaml
- back/src/ValueObject/ToDo/Item.php
> feat: import todo

- back/src/ValueObject/ToDo/Item.php
- back/templates/list_imported_data/include/data_table.html.twig
> feat: add date format in import page

- back/bin/commandZipPicture.php
> fix: change log zip

- back/src/Service/Picture/ZipAllPictureDirectory.php
> feat: correct timeout zip
